title: Minjeong Kim
url: "https://github.com/kmmnjng528"
baseurl: ""

markdown: kramdown
ins_logo: "./logo.png"

tracking_id: UA-138665784-2 #

footer: no
footer_url: "https://github.com/kmmnjng528"
footer_text: "Minjeong Kim"

sass:
    style: compressed
    sass_dir: _sass

remote_theme: ankitsultana/researcher@gem

theme: jekyll-theme-cayman
